### ISSUE TITLE
你好能否在SCefBrowser类中开放CreateWindow和CloseWindow这两个事件

### ISSUE THREAD

**Issue by yudonghai200** [aSurgingRiver/WebView#10]
有幸使用您的WebView插件，对于单页面的场景是没问题的，但是如果多页面情况下没法创建子页面，就没法适用于多页面的场景。

**Comment by aSurgingRiver** [comment]
可以加我微信 aSurgingRiver 或者qq 249838628  详聊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月17日 14:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [aSurgingRiver/WebView] 你好能否在SCefBrowser类中开放CreateWindow和CloseWindow这两个事件 (Issue #10) |

有幸使用您的WebView插件，对于单页面的场景是没问题的，但是如果多页面情况下没法创建子页面，就没法适用于多页面的场景。
