### ISSUE TITLE
分辨率缩放问题

### ISSUE THREAD

**Issue by fy0** [aSurgingRiver/WebView#11]
你好，目前刚接手一个公司项目，用到了webview。

但是有一种奇怪的现象：当分辨率变化时，webview会先跟着缩放，然后网页内容回弹成原本的分辨率，而不会自适应。

目前我对项目细节仍未十分了解，请问这种现象是webview本身的机制或选项所致吗？如果是的话，能否规避

**Comment by aSurgingRiver** [comment]
请检查WebView在编辑器中的设置。Web pixel 如果设置成大于 128*64  网页渲染出来的大小会固定，否则网页渲染由浏览器自动适应。
















在 2022-06-11 21:03:37，"fy" ***@***.***> 写道：

你好，目前刚接手一个公司项目，用到了webview。

但是有一种奇怪的现象：当分辨率变化时，webview会先跟着缩放，然后网页内容回弹成原本的分辨率，而不会自适应。

目前我对项目细节仍未十分了解，请问这种现象是webview本身的机制或选项所致吗？如果是的话，能否规避
