### ISSUE TITLE
打开程序报错  无法定位程序输入点 clearReportBetween_ExportThunk 于动态链接库

### ISSUE THREAD

**Issue by ouyangxuxiang** [aSurgingRiver/WebView#13]
最终指向 cef_95.4638\win64\lib\libcef.dll

**Comment by aSurgingRiver** [comment]
https://www.zhihu.com/column/c_1490114276946223104
请查看专栏中 加载并启动章节。
这个错误是由于你启动了WebView插件以外的其他浏览器插件。请将这些插件关闭。只保留WebView
















在 2022-07-02 14:50:14，"ouyangxuxiang" ***@***.***> 写道：

最终指向 cef_95.4638\win64\lib\libcef.dll
