### ISSUE TITLE
UnrealEditor.exe has triggered a breakpoint. and stacked in 75%

### ISSUE THREAD

**Issue by yassineMessaoud9** [aSurgingRiver/WebView#18]
Fatal error: [File:G:\plugin\build\product\WebView_6099_Win64_UE_5.0_20240219\HostProject\Plugins\WebView\Source\CefBrowser\Private\WidgetWrap\CefBrowserSingleton.cpp] [Line: 374] 
FCefBrowserSingleton::InitInter Plugins={Bridge|../../../Engine/Plugins/Bridge                 *** disable plugin 
FastBuildController|../../../Engine/Plugins/FastBuildController
MeshPainting|../../../Engine/Plugins/MeshPainting
XGEController|../../../Engine/Plugins/XGEController
AISupport|../../../Engine/Plugins/AI/AISupport
EnvironmentQueryEditor|../../../Engine/Plugins/AI/EnvironmentQueryEditor
Paper2D|../../../Engine/Plugins/2D/Paper2D
AnimationModifierLibrary|../../../Engine/Plugins/Animation/AnimationModifierLibrary
ControlRig|../../../Engine/Plugins/Animation/ControlRig
ControlRigSpline|../../../Engine/Plugins/Animation/ControlRigSpline
BlendSpaceMotionAnalysis|../../../Engine/Plugins/Animation/BlendSpaceMotionAnalysis
IKRig|../../../Engine/Plugins/Animation/IKRig
LiveLink|../../../Engine/Plugins/Animation/LiveLink
CameraShakePreviewer|../../../Engine/Plugins/Cameras/CameraShakePreviewer
GameplayCameras|../../../Engine/Plugins/Cameras/GameplayCameras
OodleNetwork|../../../Engine/Plugins/Compression/OodleNetwork
AnimationSharing|../../../Engine/Plugins/Developer/AnimationSharing
CodeLiteSourceCodeAccess|../../../Engine/Plugins/Developer/CodeLiteSourceCodeAccess
CLionSourceCodeAccess|../../../Engine/Plugins/Developer/CLionSourceCodeAccess
GitSourceControl|../../../Engine/Plugins/Developer/GitSourceControl
KDevelopSourceCodeAccess|../../../Engine/Plugins/Developer/KDevelopSourceCodeAccess
PerforceSourceControl|../../../Engine/Plugins/Developer/PerforceSourceControl
PixWinPlugin|../../../Engine/Plugins/Developer/PixWinPlugin
PluginUtils|../../../Engine/Plugins/Developer/PluginUtils
PlasticSourceControl|../../../Engine/Plugins/Developer/PlasticSourceControl
PropertyAccessNode|../../../Engine/Plugins/Developer/PropertyAccessNode
RiderSourceCodeAccess|../../../Engine/Plugins/Developer/RiderSourceCodeAccess
TextureFormatOodle|../../../Engine/Plugins/Developer/TextureFormatOodle
SubversionSourceControl|../../../Engine/Plugins/Developer/SubversionSourceControl
TraceDataFilters|../../../Engine/Plugins/Developer/TraceDataFiltering
UObjectPlugin|../../../Engine/Plugins/Developer/UObjectPlugin
VisualStudioCodeSourceCodeAccess|../../../Engine/Plugins/Developer/VisualStudioCodeSourceCodeAccess
XCodeSourceCodeAccess|../../../Engine/Plugins/Developer/XCodeSourceCodeAccess
AssetManagerEditor|../../../Engine/Plugins/Editor/AssetManagerEditor
VisualStudioSourceCodeAccess|../../../Engine/Plugins/Developer/VisualStudioSourceCodeAccess
CryptoKeys|../../../Engine/Plugins/Editor/CryptoKeys
CurveEditorTools|../../../Engine/Plugins/Editor/CurveEditorTools
NullSourceCodeAccess|../../../Engine/Plugins/Developer/NullSourceCodeAccess
EditorDebugTools|../../../Engine/Plugins/Editor/EditorDebugTools
FacialAnimation|../../../Engine/Plugins/Editor/FacialAnimation
GameplayTagsEditor|../../../Engine/Plugins/Editor/GameplayTagsEditor
MacGraphicsSwitching|../../../Engine/Plugins/Editor/MacGraphicsSwitching
DataValidation|../../../Engine/Plugins/Editor/DataValidation
EditorScriptingUtilities|../../../Engine/Plugins/Editor/EditorScriptingUtilities
GeometryMode|../../../Engine/Plugins/Editor/GeometryMode
MaterialAnalyzer|../../../Engine/Plugins/Editor/MaterialAnalyzer
MobileLauncherProfileWizard|../../../Engine/Plugins/Editor/MobileLauncherProfileWizard
SequencerAnimTools|../../../Engine/Plugins/Editor/SequencerAnimTools
PluginBrowser|../../../Engine/Plugins/Editor/PluginBrowser
WorldPartitionHLODUtilities|../../../Engine/Plugins/Editor/WorldPartitionHLODUtilities
DatasmithContent|../../../Engine/Plugins/Enterprise/DatasmithContent
SpeedTreeImporter|../../../Engine/Plugins/Editor/SpeedTreeImporter
VariantManagerContent|../../../Engine/Plugins/Enterprise/VariantManagerContent
AutomationUtils|../../../Engine/Plugins/Experimental/AutomationUtils
BackChannel|../../../Engine/Plugins/Experimental/BackChannel
ChaosCloth|../../../Engine/Plugins/Experimental/ChaosCloth
ChaosClothEditor|../../../Engine/Plugins/Experimental/ChaosClothEditor
ChaosNiagara|../../../Engine/Plugins/Experimental/ChaosNiagara
ChaosSolverPlugin|../../../Engine/Plugins/Experimental/ChaosSol
UnrealEditor.exe has triggered a breakpoint.

**Comment by aSurgingRiver** [comment]
Please follow the steps below to operate：
1. Disable webview in the upproject file and enter the UE editor.
2. Disable Bridge in the plugin
3. Start the WebView plugin
4. Restart the project

**Comment by aSurgingRiver** [comment]
WebView conflicts with the official WebBrowser browser and cannot be used simultaneously. Bridge uses the official WebBrowser kernel.

**Comment by yassineMessaoud9** [comment]
> WebView conflicts with the official WebBrowser browser and cannot be used simultaneously. Bridge uses the official WebBrowser kernel.

'UnrealEditor.exe' (Win32): Loaded 'C:\Program Files\Epic Games\UE_5.0\Engine\Plugins\Runtime\AR\Google\GoogleARCore\Binaries\Win64\UnrealEditor-GoogleARCoreBase.dll'. 
[2024.02.22-14.13.05:114][  0]WebViewLog: Version publish date [01:37:01 Feb 19 2024]
[2024.02.22-14.13.05:115][  0]WebViewLog: don't find license file
[2024.02.22-14.13.05:115][  0]WebViewLog: Load license state 0
'UnrealEditor.exe' (Win32): Loaded 'C:\Windows\System32\wbem\wbemprox.dll'. 
'UnrealEditor.exe' (Win32): Loaded 'C:\Windows\System32\wbemcomn.dll'. 
'UnrealEditor.exe' (Win32): Loaded 'C:\Windows\System32\wbem\wbemsvc.dll'. 
'UnrealEditor.exe' (Win32): Loaded 'C:\Windows\System32\wbem\fastprox.dll'. 
'UnrealEditor.exe' (Win32): Loaded 'C:\Windows\System32\amsi.dll'. 
'UnrealEditor.exe' (Win32): Loaded 'C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23110.3-0\MpOAV.dll'. 
[2024.02.22-14.13.06:675][  0]WebViewLog: local machine code diskid{3989PSD8T - 0100_0000_0000_0000_8CE3_8E04_005F_CBED.}
[2024.02.22-14.13.06:676][  0]WebViewLog: local machine code cpu{178BFBFF00810F81}
[2024.02.22-14.13.06:676][  0]WebViewLog: local machine code board{KA41NRCV006HUEMB}
[2024.02.22-14.13.06:677][  0]WebViewLog: local machine code mac{04:D4:C4:E9:E9:7A - C0:E4:34:1B:9C:20 - C0:E4:34:1B:9C:21}
Exception thrown at 0x00007FF8AFC5CF19 (KernelBase.dll) in UnrealEditor.exe: 0xC06D007E: Module not found (parameters: 0x000000AC0DE0F0A0).
Unhandled exception at 0x00007FF8AFC5CF19 (KernelBase.dll) in UnrealEditor.exe: 0xC06D007E: Module not found (parameters: 0x000000AC0DE0F0A0).

**Comment by aSurgingRiver** [comment]
WebView is a commercial paid plugin that cannot be packaged without authorization and has watermarks at runtime.
If you would like to purchase consultation, please contact us via email aSurgingRiver@gmail.com
