### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by xiaoniu1235** [aSurgingRiver/WebView#2]
1：只看到windows版本，有android和ios版本吗？
2：为什么不提供js和C++直接交互？cef本身就有这个功能的呀！

**Comment by aSurgingRiver** [comment]
感谢你宝贵的建议：
1. CEF框架自身只支持window、linux、ios，对于android没有对应的支持。UE官方的版本通过android原生的webview支持android平台的。另外目前开发人力有限只开发了windows版本平台。后续人力充足情况下考虑扩展其他平台。
2. 这个插件已经对js和C++交互提供了封装，直接交互的话对大多数不熟悉V8架构的人增加了使用成本。目前这种方案也是UE官方推荐的方案，可以快速的集成JS到UE中。降低了使用上的门槛。
















在 2022-02-08 16:57:24，"xiaoniu1235" ***@***.***> 写道：

1：只看到windows版本，有android和ios版本吗？
2：为什么不提供js和C++直接交互？cef本身就有这个功能的呀！

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaoniu1235** [comment]
官方的webview方案，有些地方用起来很麻烦
1：js不能直接调用C++函数，需要蓝图里转下
2：蓝图函数的返回值，js只能通过异步方式获取，这导致js代码很难写
你们可以参考腾讯的puerts项目，能很好的支持跨平台，使用起来很方便，可惜的是，我没找到对webview的支持！
官方的方案，总得来说是能用，但不好用，希望你们能做的更好！

**Comment by aSurgingRiver** [comment]
官方的实现中，在linux和windows平台通过封装CEF实现，对于Mac和android平台均通过封装各自平台的浏览器实现。所以他们在内部实现不一致。
puerts的确不错，底层通过V8引擎实现解决跨平台的问题。但CEF框架不支持android平台，所以不能用一套代码解决跨平台问题。
















在 2022-02-09 12:17:44，"xiaoniu1235" ***@***.***> 写道：

官方的webview方案，有些地方用起来很麻烦
1：js不能直接调用C++函数，需要蓝图里转下
2：蓝图函数的返回值，js只能通过异步方式获取，这导致js代码很难写
你们可以参考腾讯的puerts项目，能很好的支持跨平台，使用起来很方便，可惜的是，我没找到对webview的支持！
官方的方案，总得来说是能用，但不好用，希望你们能做的更好！

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hanleon** [comment]
@aSurgingRiver 请问这个4.27版本支持打包iOS吗？

**Comment by aSurgingRiver** [comment]
目前仅支持Windows系统，其他系统后续会支持。
















At 2022-03-10 16:20:47, "Hanleon" ***@***.***> wrote:

@aSurgingRiver 请问这个4.27版本支持打包iOS吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
