### ISSUE TITLE
Android Device Support

### ISSUE THREAD

**Issue by Mr11647** [aSurgingRiver/WebView#22]

**Comment by Mr11647** [comment]
Hi does it work for android mobile devices as well? the original web browser of unreal engine turns black when put inside an actor and spawned inside the level

**Comment by Mr11647** [comment]
its for an AR app this web browser is need to be spawned inside the level

**Comment by aSurgingRiver** [comment]
this plug don't support mobile device. Except for the official browser, other plug-ins are not supported.

**Comment by aSurgingRiver** [comment]
This plugin does not support mobile devices, including Android and iOS. If you want to support it, please use the official browser. Other plugins do not support mobile devices.

**Comment by Mr11647** [comment]
ok thanks
