### ISSUE TITLE
Resources usage in the background

### ISSUE THREAD

**Issue by kubalobo** [aSurgingRiver/WebView#28]
Hi!

Thank you for the fantastic plugin. \
Two things concern me about the way the plugin works in the background.

1) 
Constant CPU usage:
When the plugin is **disabled** and Unreal Editor minimalized, it uses about 0% of CPU resources.
![image](https://github.com/user-attachments/assets/c8602df2-abf8-4058-8d7e-cf90985c7956)

When the plugin is **enabled** and Unreal Editor minimalized, it constantly uses about 10% of CPU resources.
![image](https://github.com/user-attachments/assets/4d60b4ae-0cb1-491c-87c1-60c85317203d)

2)
Spawning a lot of cefbrowser-related background processes which are not killed after disabling Unreal Editor:
![image](https://github.com/user-attachments/assets/3dfda56e-2221-4bb5-b48b-8b4b6b1f7bab)
They do not consume resources, so are unharming but still, it would be nice not to leave them working ;)

Are these behaviours expected? \
Is there anything I can do about that?

Best regards!

**Comment by aSurgingRiver** [comment]
1. The WebView plug-in has very low CPU usage in the editor.
2. All embedded browsers that rely on the CEF kernel will generate related working processes in the background, which are required for CEF to run.
3. The background process names shown in the third picture are not the background processes of our plug-in.

The screenshots provided in the attachment are the CPU usage of WebView and the background processes.

![image](https://github.com/user-attachments/assets/4176fc1d-1503-482c-9e80-9f77c795ba0a)

**Comment by kubalobo** [comment]
Hi, thank you for the reply.

Regarding background usage of resources, the plugin update solved the problem on my side. I previously used the version from 2024/08/22, now 2024/11/24.

Background processes, indeed, aren't related. The name fooled me. Sorry for the false alarm.

Thanks again!

**Comment by aSurgingRiver** [comment]
If the WebView plugin is helpful to you, please give it a five-star rating.

https://www.fab.com/zh-cn/listings/a9bddc57-1f05-4b92-8735-bbb048c66c16
