### ISSUE TITLE
UE5 Preview 1

### ISSUE THREAD

**Issue by maschere** [aSurgingRiver/WebView#6]
Upon adding the UWebViewWidget to UMG I get the error: 
`CoreWebLog: Error: FCefBrowserSingleton::CreateBrowserWindow timeout.`

In game, the browser window is stuck at "loading page".

**Comment by maschere** [comment]
I figured out the cause of the problem: If you enable the default "WebBrowserWidget" by Epic, then this error occurs (the CEF version probably clash then). So disabling that is a simple workaround for now.

**Comment by aSurgingRiver** [comment]
The ue5 preview version opens the WebBrowser plug-in by default. To use the WebView plug-in, you need to disable the WebBrowser plug-in first.

**Comment by aSurgingRiver** [comment]
> The ue5 preview version opens the WebBrowser plug-in by default. To use the WebView plug-in, you need to disable the WebBrowser plug-in first.
