### ISSUE TITLE
虚幻浏览器插件 本地域名解析 错误

### ISSUE THREAD

**Issue by kangxinghua** [aSurgingRiver/WebView#8]
不管是4.26版本还是5.0 
按照https://zhuanlan.zhihu.com/p/493447586
步骤使用都无法正常使用。
有以下两个特点：
1、如果我把项目放到我用户目录，则地址栏上会出现：
http://../Users/用户名/Documents/UE5Demo/Content/webpage/control.html
2、如果我把项目放到D盘上，则地址栏直接显示：local://control.html

**Comment by aSurgingRiver** [comment]
你什么时候更新的版本。这个功能必须4.5号以后的才支持。
如果方便的话可以加我QQ: 249838628  交流
















在 2022-04-07 20:05:17，"kangxinghua" ***@***.***> 写道：

不管是4.26版本还是5.0
按照https://zhuanlan.zhihu.com/p/493447586
步骤使用都无法正常使用。
有以下两个特点：
1、如果我把项目放到我用户目录，则地址栏上会出现：
http://../Users/用户名/Documents/UE5Demo/Content/webpage/control.html
2、如果我把项目放到D盘上，则地址栏直接显示：local://control.html
